// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
  "swagger": "2.0",
  "info": {
    "description": "End Points API for microservice x kubernetes study.",
    "title": "EndPoints API",
    "version": "0.1.0"
  },
  "paths": {
    "/checkList" : {
	  "get": {
 		"summary":"get all endpoint list",
		"response": {
		  "200": {}
		}
	  }
	},
    "/endpoints/": {
      "get": {
        "summary": "Retrieve end point list",
        "responses": {
          "200": {}
        }
      }
    },
    "/endpoints/": {
      "post": {
        "summary": "Create new end point",
        "responses": {
          "200": {}
        }
      }
    },
    "/endpoint/{endpointId}": {
      "get": {
        "summary": "Retrieve an end point information.",
        "responses": {
          "200": {}
        }
      }
    },
    "/endpoint/{endpointId}": {
      "put": {
        "summary": "Update end point information.",
        "responses": {
          "200": {}
        }
      }
    },
    "/endpoint/{endpointId}": {
      "delete": {
        "summary": "Delete end point information.",
        "responses": {
          "200": {}
        }
      }
    }
  }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
